### ISSUE TITLE
Prism - code sign binaries for Windows and OSX

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#403]
**Chore summary**

Currently both Windows and OSX complain about unknown developers, which can make it hard to use the binaries.

Linux is fine, as most distributions do not seem to care, and there are workarounds.

**Tasks**
- [ ] Find out what credentials to sign with
- [ ] Automate signing binaries in Windows
- [ ] Automate sign binaries in OS X

**Notes**
- `pkg` created executable for macOS are not signable: https://github.com/zeit/pkg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sign Especially https://github.com/zeit/pkg/issues/128#issuecomment-534117456
- switching to Electron could be good because it handles signing with `electron-builder`, but we cannot switch to Electron, since Electron is not for packaking CLI tools. End of story
- we could switch to `nexe`, but it does seem that signing macOS executables is also somewhat not possible: https://github.com/nexe/nexe/issues/494 Might not be the case for Prism (?) since there is the talk of `resources`, but I'm not sure Prism needs any and also if it is only about `resources` being the problem or code signing doesn't work at all
- if we manage to build a package that is actually signable, then we'd probably need to spin up a macOS container in CircleCI and then for signing windows exe we could probably use https://www.npmjs.com/package/signcode and for signing macOS executable use codesign
- probably we could reuse the cert from studio-internal when we have the pass for it

**Comment by XVincentX** [comment]
@lag-of-death node-packer might be a solution as well

**Comment by lag-of-death** [comment]
- failed at trying to sign a binary with self-signed cert on a mac, was always ending up with:
  `The specified item could not be found in the keychain`. I was creating my own `.keychain` and importing `.p12` cert to that keychain and later: `codesign -s FE0A0B0F9C1410AC4A54174E197AE5F4396D180E --force ./project --keychain MyKeyChain.keychain`.
  
- tried code signing with *ad-hoc signing*: `codesign --deep --force --verbose --sign - ./project`. This didn't work because the binary was generated by standard nexe usage. So the above command failed with: `main executable failed strict validation`

- tried generating a binary with `nexe` in its slow mode (which was said to fix `main executable failed strict validation`), but slow generation was a non-finishing process. On CircleCI, got `Too long with no output (exceeded 30m0s)`, didn't work locally neither.

- looked at EncloseJS, but it only seems to support narrow range of node versions:  0.12.x, 4.2.x or 5.x.

- tried to sign a mac os binary created by pkg (what prism is using to generate a binary now), but `codesign --deep --force --verbose --sign - ./cli-binaries/macos` ends with `main executable failed strict validation`. Also tried a trick with renaming a binary to have an extension like `.old`, but this didn't work neither

- were looking for alternatives, but found nothing. Seems like I have run out of options here

- looked at NWjs, but it's like Electron, dedicated to creating windowed apps

- switched to `node-packer` for generating a binary, **it's only node-packer that seems to allow for a mac generated binary to be signed**. But **it doesn't seem to be able to generate binaries for different platforms from a single platform**. So maybe we would only use node-packer to generate the binary for macos, pkg for linux and for windows? **Maybe pkg generates a binary for windows that's signable (this is a `TODO`)?**

cc @XVincentX

**Comment by lag-of-death** [comment]
@XVincentX 

- a windows binary produced by `pkg` was signable by https://www.npmjs.com/package/signcode. So this leaves us with: binaries for windows and linux created with `pkg` and a binary for macOS created with `node-packer`. Please keep in mind that the Windows binary was signed with a self-signed cert and macos one was signed with `ad-hoc signing` as a POC. Adding in real certs will need further work. Also the found solution uses 2 different tools (`pkg` and `node-packer`) to package a binary but I have not found an alternative

**Comment by saurabh-deep** [comment]
Hey @lag-of-death - Which Node.js version are you targeting for macOS? As far as I know, node-packer has support only till Node 8.

**Comment by XVincentX** [comment]
@saurabh-deep We're not going to provide code sign. We've analysed the benefits and they're very little compared to the burden required to make this happen correctly.
