### ISSUE TITLE
Parse JSON inside `prism-http`

### ISSUE THREAD

**Issue by karol-maciaszek** [stoplightio/prism#977]
**Chore summary**
The JSON parsing logic is currently a responsibility of `prism-http` library clients. Here is how it looks in `prism-http-server`: https://github.com/stoplightio/prism/blob/master/packages/http-server/src/server.ts#L41. The goal is to move that logic to `prism-http`.

The reason behind:
- modules should have clear interface, having an exception for JSONish content is not clear for the user
- detecting a JSON is tricky, content-type might be `application/something+json`
- a client of `prism-http` might not be aware that he needs to detect JSON content and parse it. It just adds complexity

**Tasks**
- [ ] Move detecting and parsing of JSON content to `prism-http` module
- [ ] Change types, so that body must be a string (or undefined)
- [ ] Remove parsing logic from `prism-http-server`
- [ ] remove parsing logic from `request-maker` (introduced in https://github.com/stoplightio/request-maker/pull/149)

**Comment by chohmann** [comment]
Closing as this is as it is not relevant anymore.
